### ISSUE TITLE
Generate LEF files

### ISSUE THREAD

**Issue by urielcho** [mattvenn/logo-to-gds2#3]
Hi, I'm trying to generate the gds and lef files for use in openlane projects.
I can generate the gds files correctly, but I have no idea how to make the lef files.
Could you tell me how can I do it please?

**Comment by mattvenn** [comment]
isn't that handled by the make file? https://github.com/mattvenn/logo-to-gds2/blob/5ba3a308867bd7d1f513097cc8145da9a86b1083/Makefile#L18

**Comment by urielcho** [comment]
If I use this command, I get the following.
![Captura de pantalla de 2022-12-12 08-19-41](https://user-images.githubusercontent.com/106149461/207068762-38c4de57-d532-412c-8b42-76631b26f183.png)

**Comment by mattvenn** [comment]
is LOGO.mag present? Magic is complaining it can't find it. If you've changed the names of the GDS then you'll probably need to change the tcl file as well: https://github.com/mattvenn/logo-to-gds2/blob/5ba3a308867bd7d1f513097cc8145da9a86b1083/save_lef.tcl

**Comment by urielcho** [comment]
How can I know if LOGO.mag is being created correctly?

I'm trying to use the example file with the make logo_svg.lef command and it doesn't work either?

**Comment by mattvenn** [comment]
I just tested it locally with MPW8 versions of PDK and Magic.
I had different errors, which I fixed with a change to the Makefile.

**Comment by urielcho** [comment]
I still get the same problem, how can I check that the .mag file is created correctly?
